// Réception HTTP sur Postgres local jetable ; aucun fournisseur ni dossier réel.
import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { createServer } from 'node:net';
import { createServer as createHttpServer } from 'node:http';
import { mkdtemp, rm, readdir, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import pg from 'pg';

const adminUrl = process.env.RADAR_TEST_ADMIN_URL;
if (!adminUrl) throw new Error('RADAR_TEST_ADMIN_URL local requis');
const target = new URL(adminUrl);
if (!['127.0.0.1', 'localhost', '[::1]'].includes(target.hostname)) throw new Error('Base de recette locale uniquement');
const name = 'shinkiro_radar_' + process.pid + '_' + Date.now();
const admin = new pg.Pool({ connectionString: adminUrl });
let db, child, origin, directory, ollama, ollamaReply=null, ollamaRequests=[], childLogs = '';
const auth = who => ({ Authorization: 'Basic ' + Buffer.from(who + '@recette.invalid:recette-locale').toString('base64') });
const req = (url, who = 'alice', method = 'GET', body) => fetch(origin + url, {
  method, headers: { ...(who ? auth(who) : {}), ...(body ? { 'Content-Type': 'application/json', Prefer: 'return=representation' } : {}) },
  ...(body ? { body: JSON.stringify(body) } : {}),
});

async function startChild(port) {
  child = spawn(process.execPath, ['server/index.js'], { cwd: new URL('../', import.meta.url),
    env: { ...process.env, DATABASE_URL: target.href, PORT: String(port), HOST: '127.0.0.1', SQLITE_PATH: path.join(directory, 'users.sqlite'),
      VISUELS_DIR: path.join(directory, 'visuels'), DASH_PASSWORD: 'recette-locale', DASH_COOKIE_SECRET: 'signature-de-recette',
      TZ: 'Africa/Douala', RADAR_API_KEY: 'machine-de-recette', FEED_TOKEN: '', RADAR_SEED_CSV: '', OLLAMA_URL: 'http://127.0.0.1:'+ollama.address().port,
      RADAR_AUTHZ_JSON: JSON.stringify({ 'alice@recette.invalid': { person: 'Alice Recette', role: 'owner' },
        'bob@recette.invalid': { person: 'Bob Recette', role: 'member' },
        'sue@recette.invalid': { person: 'Sue Recette', role: 'supervisor' },
        'empty@recette.invalid': { person: '', role: 'member' } }),
    }, stdio: ['ignore', 'pipe', 'pipe'] });
  child.stdout.on('data', b => { childLogs += b; }); child.stderr.on('data', b => { childLogs += b; });
  for (let i = 0; i < 100; i++) {
    try { const r = await req('/rest/v1/briefs?limit=0'); if (r.ok) return; } catch {}
    if (child.exitCode !== null) throw new Error(childLogs);
    await new Promise(r => setTimeout(r, 100));
  }
  throw new Error('Serveur de recette indisponible : ' + childLogs);
}
async function stopChild() {
  if (child && child.exitCode === null) { child.kill('SIGTERM'); await once(child, 'exit'); }
}
before(async () => {
  await admin.query('create database ' + name);
  target.pathname = '/' + name;
  db = new pg.Pool({ connectionString: target.href });
  // Contrat du journal déjà déployé : 12 colonnes, aucune qualification historique.
  await db.query(`create table task_events (
    id bigint generated by default as identity primary key, at timestamptz default now(),
    ndeg text, entree text, client text, projet text, kind text,
    statut_old text, statut_new text, resp_old text, resp_new text, summary text)`);
  await db.query("insert into task_events(ndeg,projet,kind) select 'REC-ANCIEN-'||n,'ANCIEN_NON_QUALIFIE','created' from generate_series(1,125) n");
  directory = await mkdtemp(path.join(tmpdir(), 'radar-reception-'));
  const socket = createServer(); socket.listen(0, '127.0.0.1'); await once(socket, 'listening');
  const port = socket.address().port; await new Promise(r => socket.close(r)); origin = 'http://127.0.0.1:' + port;
  ollama=createHttpServer(async (req,res)=>{
    let body=''; for await (const chunk of req) body+=chunk;
    ollamaRequests.push(JSON.parse(body));
    if (!ollamaReply) { res.writeHead(503); res.end('Simulateur indisponible'); return; }
    res.setHeader('Content-Type','application/json'); res.end(JSON.stringify({message:{content:JSON.stringify(ollamaReply)}}));
  });
  ollama.listen(0,'127.0.0.1'); await once(ollama,'listening');
  await startChild(port);
});

after(async () => {
  await stopChild();
  if (ollama) await new Promise(r=>ollama.close(r));
  if (db) await db.end();
  await admin.query('drop database if exists ' + name); await admin.end();
  if (directory) await rm(directory, { recursive: true, force: true });
});

test('un changement et son journal échouent ensemble, sans faux reçu HTTP', async () => {
  await db.query("alter table task_events add constraint recette_journal_failure check (kind <> 'created') not valid");
  try {
    const response = await req('/rest/v1/briefs', 'alice', 'POST', { ndeg: 'REC-FAIL', projet: 'Écriture de recette', statut: 'Reçu' });
    assert.equal(response.status, 500);
    assert.equal((await db.query("select count(*)::int as n from briefs where ndeg='REC-FAIL'")).rows[0].n, 0);
  } finally { await db.query('alter table task_events drop constraint recette_journal_failure'); }
});

test('un corps sans colonne reconnue ne crée pas de dossier vide', async () => {
  const n = (await db.query('select count(*)::int as n from briefs')).rows[0].n;
  assert.equal((await req('/rest/v1/briefs', 'alice', 'POST', { destination_inconnue: 'Recette' })).status, 400);
  assert.equal((await db.query('select count(*)::int as n from briefs')).rows[0].n, n);
});

test('le journal ne peut pas être écrit ou réécrit depuis REST', async () => {
  assert.equal((await req('/rest/v1/task_events', 'alice', 'POST', { ndeg: 'FAUX', kind: 'closed' })).status, 405);
  assert.equal((await req('/rest/v1/task_events?id=eq.1', 'alice', 'PATCH', { summary: 'Accord inventé' })).status, 405);
});

test('une dépêche privée reste absente du flux public et du journal de Bob', async () => {
  const r = await req('/rest/v1/briefs', 'alice', 'POST', { ndeg: 'REC-PRIVE', projet: 'CONFIDENTIEL_RECETTE', private_to: 'Alice Recette', statut: 'Reçu' });
  assert.equal(r.status, 201);
  const publicFeed = await (await req('/activity.json', null)).text();
  assert.ok(!publicFeed.includes('CONFIDENTIEL_RECETTE'));
  const bob = await (await req('/rest/v1/task_events?ndeg=eq.REC-PRIVE', 'bob')).json();
  assert.equal(bob.length, 0);
  const alice = await (await req('/rest/v1/task_events?ndeg=eq.REC-PRIVE')).json();
  assert.equal(alice.length, 1);
});

const png = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j1ioAAAAASUVORK5CYII=';

test('connaître un nom de fichier privé ne donne pas accès à son binaire', async () => {
  if (!(await db.query("select 1 from briefs where ndeg='REC-PRIVE'")).rowCount) {
    await db.query("insert into briefs(ndeg,projet,private_to) values ('REC-PRIVE','CONFIDENTIEL_RECETTE','Alice Recette')");
  }
  const upload = await req('/visuels', 'alice', 'POST', { ndeg: 'REC-PRIVE', data: png, caption: 'Image synthétique' });
  assert.equal(upload.status, 201); const asset = await upload.json();
  assert.equal((await req('/visuels/' + asset.filename, 'bob')).status, 404);
  const own = await req('/visuels/' + asset.filename);
  assert.equal(own.status, 200); assert.match(own.headers.get('cache-control'), /private|no-store/);
});


test('SQL, REST et import utilisent le même journal, sans doublon ni faux mouvement', async () => {
  const created = await (await req('/rest/v1/briefs', 'alice', 'POST', { ndeg: 'REC-UNIQUE', projet: 'Manuel', statut: 'Reçu' })).json();
  const id = created[0].id;
  assert.equal((await db.query('select count(*)::int as n from task_events where brief_id=$1', [id])).rows[0].n, 1);
  assert.equal((await req('/rest/v1/briefs?id=eq.' + id, 'alice', 'PATCH', { statut: 'Reçu' })).status, 200);
  assert.equal((await db.query('select count(*)::int as n from task_events where brief_id=$1', [id])).rows[0].n, 1);
  await db.query('update briefs set statut=$1 where id=$2', ['En cours', id]);
  const events = (await db.query('select kind,statut_old,statut_new from task_events where brief_id=$1 order by id', [id])).rows;
  assert.deepEqual(events.map(e=>e.kind), ['created','status']);
  assert.equal(events[1].statut_old, 'Reçu'); assert.equal(events[1].statut_new, 'En cours');
  const ingest = await req('/ingest', 'alice', 'POST', { text: 'Retour synthétique brut conservé, sans modèle.', client: 'Recette' });
  assert.equal(ingest.status, 201); const result = await ingest.json(); assert.equal(result.fallback, true);
  assert.equal((await db.query('select count(*)::int as n from task_events where ndeg=$1',[result.created[0].ndeg])).rows[0].n, 1);
});

test('un import brut échoue sans dossier résiduel lorsque sa trace est refusée', async () => {
  const n = (await db.query('select count(*)::int as n from briefs')).rows[0].n;
  await db.query("alter table task_events add constraint recette_ingest_failure check (kind <> 'created') not valid");
  try {
    assert.equal((await req('/ingest', 'alice', 'POST', { text: 'Recette sans succès inventé.' })).status, 500);
    assert.equal((await db.query('select count(*)::int as n from briefs')).rows[0].n, n);
  } finally { await db.query('alter table task_events drop constraint recette_ingest_failure'); }
});

test('les 125 événements anciens restent conservés, non publiés et signalés comme incomplets', async () => {
  const http = await req('/rest/v1/task_events?ndeg=like.REC-ANCIEN-%');
  assert.equal(http.headers.get('x-radar-unqualified-events'), '125'); assert.deepEqual(await http.json(), []);
  const feed = await (await req('/activity.json', null)).json();
  assert.equal(feed._radar.unqualified_events,125); assert.equal(feed._radar.history_complete,false);
  assert.ok(!JSON.stringify(feed.items).includes('ANCIEN_NON_QUALIFIE'));
  const rss = await (await req('/feed.xml', null)).text();
  assert.ok(rss.includes('125 événements anciens à qualifier')); assert.ok(!rss.includes('ANCIEN_NON_QUALIFIE'));
  assert.equal((await db.query('select count(*)::int as n from task_events where private_to is null')).rows[0].n,125);
  const migration = await readFile(new URL('../server/journal.sql', import.meta.url), 'utf8');
  await db.query(migration); await db.query(migration);
  assert.equal((await db.query('select count(*)::int as n from task_events where private_to is null')).rows[0].n,125);
  await db.query("insert into briefs(ndeg,projet) values ('REC-RESTART','Recette migration répétée')");
  assert.equal((await db.query("select count(*)::int as n from task_events where ndeg='REC-RESTART'")).rows[0].n,1);
});

test('privé vers public ne republie pas les anciens événements privés', async () => {
  await db.query("insert into briefs(ndeg,projet,private_to) values ('REC-OUVERT','AVANT_OUVERTURE_PRIVE','Alice Recette')");
  await db.query("update briefs set private_to='',projet='APRES_OUVERTURE_PUBLIC' where ndeg='REC-OUVERT'");
  let feed = await (await req('/activity.json',null)).text();
  assert.ok(!feed.includes('AVANT_OUVERTURE_PRIVE')); assert.ok(!feed.includes('APRES_OUVERTURE_PUBLIC'));
  await db.query("update briefs set statut='En cours' where ndeg='REC-OUVERT'");
  feed = await (await req('/activity.json',null)).text();
  assert.ok(feed.includes('APRES_OUVERTURE_PUBLIC')); assert.ok(!feed.includes('AVANT_OUVERTURE_PRIVE'));
});

test('un dossier devenu privé masque son ancien journal public, même après suppression privée', async () => {
  await db.query("insert into briefs(ndeg,projet) values ('REC-FERME','PUBLIC_PUIS_PRIVE')");
  assert.ok((await (await req('/activity.json',null)).text()).includes('PUBLIC_PUIS_PRIVE'));
  await db.query("update briefs set private_to='Alice Recette' where ndeg='REC-FERME'");
  assert.ok(!(await (await req('/activity.json',null)).text()).includes('PUBLIC_PUIS_PRIVE'));
  assert.deepEqual(await (await req('/rest/v1/task_events?ndeg=eq.REC-FERME','bob')).json(),[]);
  await db.query("delete from briefs where ndeg='REC-FERME'");
  assert.ok(!(await (await req('/activity.json',null)).text()).includes('PUBLIC_PUIS_PRIVE'));
  assert.deepEqual(await (await req('/rest/v1/task_events?ndeg=eq.REC-FERME','bob')).json(),[]);
  assert.equal((await (await req('/rest/v1/task_events?ndeg=eq.REC-FERME')).json()).length,3);
});

test('la suppression publique garde une trace stable malgré la réutilisation du code', async () => {
  const original = (await db.query("insert into briefs(ndeg,projet) values ('REC-REUSE','SUPPRESSION_PUBLIQUE') returning id")).rows[0];
  await db.query('delete from briefs where id=$1',[original.id]);
  await db.query("insert into briefs(ndeg,projet,private_to) values ('REC-REUSE','AUTRE_DOSSIER_PRIVE','Alice Recette')");
  const feed = await (await req('/activity.json?kind=deleted',null)).text();
  assert.ok(feed.includes('SUPPRESSION_PUBLIQUE')); assert.ok(!feed.includes('AUTRE_DOSSIER_PRIVE'));
  assert.equal((await db.query("select brief_id from task_events where ndeg='REC-REUSE' and kind='deleted'")).rows[0].brief_id,original.id);
});

test('un échec du journal média annule les métadonnées et nettoie le fichier neuf', async () => {
  const files = await readdir(path.join(directory,'visuels'));
  const count = (await db.query('select count(*)::int as n from brief_assets')).rows[0].n;
  await db.query("alter table task_events add constraint recette_asset_failure check (kind <> 'asset') not valid");
  try {
    assert.equal((await req('/visuels','alice','POST',{ndeg:'REC-PRIVE',data:png})).status,500);
    assert.equal((await db.query('select count(*)::int as n from brief_assets')).rows[0].n,count);
    assert.deepEqual(await readdir(path.join(directory,'visuels')),files);
  } finally { await db.query('alter table task_events drop constraint recette_asset_failure'); }
});

test('la suppression média refusée par le journal conserve la ligne et le binaire', async () => {
  const a=(await db.query("select * from brief_assets where ndeg='REC-PRIVE' order by id limit 1")).rows[0];
  await db.query("alter table task_events add constraint recette_delete_failure check (kind <> 'asset_deleted')");
  try {
    assert.equal((await req('/visuels/'+a.id,'alice','DELETE')).status,500);
    assert.equal((await db.query('select count(*)::int as n from brief_assets where id=$1',[a.id])).rows[0].n,1);
    assert.equal((await req('/visuels/'+a.filename)).status,200);
  } finally { await db.query('alter table task_events drop constraint recette_delete_failure'); }
  assert.equal((await req('/visuels/'+a.id,'bob','DELETE')).status,403);
  assert.equal((await req('/visuels/'+a.id,'alice','DELETE')).status,200);
  assert.equal((await req('/visuels/'+a.filename)).status,404);
});

test('un code ambigu ne permet pas de rattacher un binaire au premier dossier trouvé', async () => {
  await db.query("insert into briefs(ndeg,projet,private_to) values ('REC-DOUBLE','Un public',''),('REC-DOUBLE','Un privé','Alice Recette')");
  assert.equal((await req('/visuels','alice','POST',{ndeg:'REC-DOUBLE',data:png})).status,409);
  await db.query("insert into brief_assets(ndeg,filename,mime) values ('REC-DOUBLE','00000000-0000-0000-0000-000000000000.png','image/png')");
  assert.deepEqual(await (await req('/rest/v1/brief_assets?ndeg=eq.REC-DOUBLE','bob')).json(),[]);
  assert.equal((await req('/visuels/00000000-0000-0000-0000-000000000000.png','bob')).status,404);
});

test('une légende ne permet pas de déplacer le fichier ou le rattachement du visuel', async () => {
  const a=(await db.query("insert into brief_assets(ndeg,filename,mime) values ('REC-UNIQUE','11111111-1111-1111-1111-111111111111.png','image/png') returning *")).rows[0];
  assert.equal((await req('/rest/v1/brief_assets?id=eq.'+a.id,'alice','PATCH',{filename:'00000000-0000-0000-0000-000000000000.png'})).status,400);
  assert.equal((await req('/rest/v1/brief_assets?id=eq.'+a.id,'alice','PATCH',{caption:'Une légende corrigée'})).status,200);
  const fresh=(await db.query('select filename,caption from brief_assets where id=$1',[a.id])).rows[0];
  assert.equal(fresh.filename,a.filename); assert.equal(fresh.caption,'Une légende corrigée');
});

test('les commentaires du dossier privé ne traversent pas le filtre REST', async () => {
  await db.query("insert into comments(ndeg,body) values ('REC-PRIVE','COMMENTAIRE_CONFIDENTIEL')");
  assert.deepEqual(await (await req('/rest/v1/comments?ndeg=eq.REC-PRIVE','bob')).json(),[]);
  assert.equal((await (await req('/rest/v1/comments?ndeg=eq.REC-PRIVE')).json()).length,1);
});

test('le filtre de confidentialité automatique ne vaut pas un filtre de mutation fourni', async () => {
  const n=(await db.query('select count(*)::int as n from briefs')).rows[0].n;
  assert.equal((await req('/rest/v1/briefs','alice','PATCH',{statut:'Frozen'})).status,400);
  assert.equal((await req('/rest/v1/briefs','alice','DELETE')).status,400);
  assert.equal((await db.query('select count(*)::int as n from briefs')).rows[0].n,n);
});

test('un lot structuré est atomique lorsque le second dossier est refusé', async () => {
  const n=(await db.query('select count(*)::int as n from briefs')).rows[0].n;
  const events=(await db.query('select count(*)::int as n from task_events')).rows[0].n;
  ollamaReply={items:[{client:'Recette',projet:'PREMIER_RECETTE'},{client:'Recette',projet:'REJET_RECETTE'}]};
  await db.query("alter table briefs add constraint recette_second_failure check(projet <> 'REJET_RECETTE') not valid");
  try {
    assert.equal((await req('/ingest','alice','POST',{text:'Deux demandes synthétiques'})).status,500);
    assert.equal((await db.query('select count(*)::int as n from briefs')).rows[0].n,n);
    assert.equal((await db.query('select count(*)::int as n from task_events')).rows[0].n,events);
  } finally { ollamaReply=null; await db.query('alter table briefs drop constraint recette_second_failure'); }
});

test('un redémarrage conserve les dossiers et le journal sans les rejouer', async () => {
  const counts=async()=> (await db.query('select (select count(*) from briefs)::int as briefs,(select count(*) from task_events)::int as events')).rows[0];
  const before=await counts(); const port=Number(new URL(origin).port);
  await stopChild(); await startChild(port);
  assert.deepEqual(await counts(),before);
  await db.query("insert into briefs(ndeg,projet) values ('REC-APRES-BOOT','Un seul mouvement après redémarrage')");
  assert.equal((await db.query("select count(*)::int as n from task_events where ndeg='REC-APRES-BOOT'")).rows[0].n,1);
});

const currentDeadline = () => new Intl.DateTimeFormat('en-CA', {timeZone:'Africa/Douala',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()).slice(0,7)+'-15';
async function fixture(code, patch={}) {
  const body={ndeg:code,projet:code,statut:'Reçu',responsable:'Bob Recette',deadline:currentDeadline(),...patch};
  const cols=Object.keys(body);
  return (await db.query(`insert into briefs (${cols.join(',')}) values (${cols.map((_,i)=>'$'+(i+1)).join(',')}) returning *`,cols.map(k=>body[k]))).rows[0];
}

test('le membre ne lit que ses tâches du mois ou ses tâches sans date encore ouvertes', async () => {
  for (const [suffix,patch] of Object.entries({
    OWN:{}, SHARED:{responsable:'Alice Recette / Bob Recette'}, ET:{responsable:'Alice Recette et Bob Recette'},
    OPEN:{deadline:'À confirmer'}, FOREIGN:{responsable:'Alice Recette'}, SUBSTRING:{responsable:'Bob Recette Junior'},
    OLD:{deadline:'2000-01-10'}, CLOSED:{deadline:'',closed_at:'2026-01-01T00:00:00Z'},
    DONE:{deadline:'',statut:'Envoyé dans Slack'}, FROZEN:{deadline:'',statut:'Gelé'},
    PRIVATE:{private_to:'Alice Recette'},
  })) await fixture('ROLE-READ-'+suffix,patch);
  const rows=await (await req('/rest/v1/briefs?ndeg=like.ROLE-READ-%','bob')).json();
  assert.deepEqual(rows.map(r=>r.ndeg).sort(),['ET','OPEN','OWN','SHARED'].map(k=>'ROLE-READ-'+k).sort());
  assert.equal((await (await req('/rest/v1/briefs?ndeg=like.ROLE-READ-%','sue')).json()).length,10);
  assert.deepEqual(await (await req('/rest/v1/briefs?ndeg=like.ROLE-READ-%','empty')).json(),[]);
  const machine=await fetch(origin+'/rest/v1/briefs?ndeg=like.ROLE-READ-%',{headers:{Authorization:'Bearer machine-de-recette'}});
  assert.equal((await machine.json()).length,11);
  assert.equal((await req('/rh/evaluation-departement.html','sue')).status,403);
});

test('réattribution étrangère et lot mixte refusés sans changement ni journal partiel', async () => {
  const own=await fixture('ROLE-PATCH-OWN');
  const other=await fixture('ROLE-PATCH-OTHER',{responsable:'Alice Recette'});
  const before=(await db.query('select count(*)::int as n from task_events')).rows[0].n;
  assert.equal((await req('/rest/v1/briefs?id=eq.'+other.id,'bob','PATCH',{responsable:'Bob Recette'})).status,403);
  assert.equal((await req('/rest/v1/briefs?id=in.('+own.id+','+other.id+')','bob','PATCH',{statut:'En cours'})).status,403);
  assert.equal((await req('/rest/v1/briefs?id=eq.'+other.id,'bob','DELETE')).status,403);
  assert.equal((await db.query('select count(*)::int as n from task_events')).rows[0].n,before);
  assert.equal((await db.query('select statut from briefs where id=$1',[own.id])).rows[0].statut,'Reçu');
  // Le responsable peut transmettre son propre travail ; l'accès cesse aussitôt.
  assert.equal((await req('/rest/v1/briefs?id=eq.'+own.id,'bob','PATCH',{responsable:'Alice Recette'})).status,200);
  assert.deepEqual(await (await req('/rest/v1/briefs?id=eq.'+own.id,'bob')).json(),[]);
  assert.equal((await req('/rest/v1/briefs?id=eq.'+own.id,'bob','PATCH',{responsable:'Bob Recette'})).status,403);
});

test('création et commentaires contrôlent leur rattachement dans la même transaction', async () => {
  await fixture('ROLE-COMMENT-OWN'); await fixture('ROLE-COMMENT-OTHER',{responsable:'Alice Recette'});
  const before=(await db.query('select count(*)::int as n from briefs')).rows[0].n;
  assert.equal((await req('/rest/v1/briefs','bob','POST',[
    {ndeg:'ROLE-CREATE-OWN',responsable:'Bob Recette',statut:'Reçu'},
    {ndeg:'ROLE-CREATE-OTHER',responsable:'Alice Recette',statut:'Reçu'},
  ])).status,403);
  assert.equal((await db.query('select count(*)::int as n from briefs')).rows[0].n,before);
  assert.equal((await req('/rest/v1/comments','bob','POST',{ndeg:'ROLE-COMMENT-OTHER',body:'Intrusion'})).status,403);
  const added=await req('/rest/v1/comments','bob','POST',{ndeg:'ROLE-COMMENT-OWN',body:'Autorisé'});
  assert.equal(added.status,201); const id=(await added.json())[0].id;
  assert.equal((await req('/rest/v1/comments?id=eq.'+id,'bob','PATCH',{ndeg:'ROLE-COMMENT-OTHER'})).status,403);
  assert.equal((await db.query('select ndeg from comments where id=$1',[id])).rows[0].ndeg,'ROLE-COMMENT-OWN');
  await db.query("update briefs set responsable='Alice Recette' where ndeg='ROLE-COMMENT-OWN'");
  assert.deepEqual(await (await req('/rest/v1/comments?id=eq.'+id,'bob')).json(),[]);
  assert.equal((await req('/rest/v1/comments?id=eq.'+id,'bob','DELETE')).status,403);
});

test('médias et légendes suivent le rôle, même après transfert du dossier', async () => {
  const brief=await fixture('ROLE-MEDIA');
  const upload=await req('/visuels','bob','POST',{ndeg:brief.ndeg,data:png});
  assert.equal(upload.status,201); const a=await upload.json();
  assert.equal((await req('/visuels/'+a.filename,'bob')).status,200);
  await db.query("update briefs set responsable='Alice Recette' where id=$1",[brief.id]);
  assert.equal((await req('/visuels/'+a.filename,'bob')).status,404);
  assert.deepEqual(await (await req('/rest/v1/brief_assets?id=eq.'+a.id,'bob')).json(),[]);
  assert.equal((await req('/rest/v1/brief_assets?id=eq.'+a.id,'bob','PATCH',{caption:'Intrusion'})).status,403);
  assert.equal((await req('/visuels/'+a.id,'bob','DELETE')).status,403);
  const files=await readdir(path.join(directory,'visuels'));
  assert.equal((await req('/visuels','bob','POST',{ndeg:brief.ndeg,data:png})).status,403);
  assert.deepEqual(await readdir(path.join(directory,'visuels')),files);
});

test('le journal applique le périmètre courant et conserve une qualification après suppression', async () => {
  const b=await fixture('ROLE-HISTORY-OWN');
  await fixture('ROLE-HISTORY-OTHER',{responsable:'Alice Recette'});
  assert.equal((await (await req('/rest/v1/task_events?ndeg=eq.'+b.ndeg,'bob')).json()).length,1);
  assert.deepEqual(await (await req('/rest/v1/task_events?ndeg=eq.ROLE-HISTORY-OTHER','bob')).json(),[]);
  await db.query('delete from briefs where id=$1',[b.id]);
  assert.equal((await (await req('/rest/v1/task_events?ndeg=eq.'+b.ndeg,'bob')).json()).length,2);
  await db.query("insert into task_events(brief_id,private_to,ndeg,kind,summary) values ($1,'',$2,'updated','SANS_QUALIFICATION_ROLE')",[b.id,b.ndeg]);
  const rows=await (await req('/rest/v1/task_events?ndeg=eq.'+b.ndeg,'bob')).json();
  assert.equal(rows.length,2); assert.ok(!JSON.stringify(rows).includes('SANS_QUALIFICATION_ROLE'));
  const transferred=await fixture('ROLE-HISTORY-TRANSFER');
  await db.query("update briefs set responsable='Alice Recette' where id=$1",[transferred.id]);
  assert.deepEqual(await (await req('/rest/v1/task_events?ndeg=eq.'+transferred.ndeg,'bob')).json(),[]);
});

test('le repli CSV sert les mêmes lignes autorisées, jamais un export brut', async () => {
  const csv=await req('/INDEX.csv','bob'); assert.equal(csv.status,200);
  assert.match(csv.headers.get('cache-control'),/no-store/);
  const text=await csv.text(); assert.ok(text.includes('ROLE-READ-OWN')); assert.ok(!text.includes('ROLE-READ-FOREIGN'));
  assert.ok(!text.includes('ROLE-READ-OLD')); assert.ok(!text.includes('CONFIDENTIEL_RECETTE'));
  const supervisor=await (await req('/INDEX.csv','sue')).text(); assert.ok(supervisor.includes('ROLE-READ-FOREIGN'));
});

test('un import membre ne transmet aucun projet étranger au modèle et reste à son nom', async () => {
  await fixture('ROLE-INGEST-OWN',{entree:'Maître',projet:'CONTEXTE_MEMBRE_AUTORISE'});
  await fixture('ROLE-INGEST-OTHER',{entree:'Maître',responsable:'Alice Recette',projet:'CONTEXTE_ETRANGER_INTERDIT'});
  const r=await req('/ingest','bob','POST',{text:'Retour membre de recette',client:'Recette'});
  assert.equal(r.status,201); const result=await r.json();
  const prompt=JSON.stringify(ollamaRequests.at(-1));
  assert.ok(prompt.includes('CONTEXTE_MEMBRE_AUTORISE')); assert.ok(!prompt.includes('CONTEXTE_ETRANGER_INTERDIT'));
  const row=(await db.query('select responsable from briefs where ndeg=$1',[result.created[0].ndeg])).rows[0];
  assert.equal(row.responsable,'Bob Recette');
  assert.equal((await (await req('/rest/v1/briefs?ndeg=eq.'+result.created[0].ndeg,'bob')).json()).length,1);
  const calls=ollamaRequests.length;
  assert.equal((await req('/ingest','empty','POST',{text:'Sans identité'})).status,403);
  assert.equal(ollamaRequests.length,calls);
});

test('une mutation en attente de verrou recontrôle le responsable après une réattribution concurrente', async () => {
  const b=await fixture('ROLE-RACE'); const lock=await db.connect();
  try {
    await lock.query('begin'); await lock.query('select id from briefs where id=$1 for update',[b.id]);
    const pending=req('/rest/v1/briefs?id=eq.'+b.id,'bob','PATCH',{projet:'INTRUSION_CONCURRENTE'});
    // Attend une vraie requête SQL bloquée, pas une durée supposée suffisante.
    let waiting=false;
    for(let i=0;i<100;i++) {
      const state=await db.query("select 1 from pg_stat_activity where datname=current_database() and wait_event_type='Lock' and pid<>pg_backend_pid()");
      if(state.rowCount) {waiting=true;break;} await new Promise(r=>setTimeout(r,20));
    }
    assert.ok(waiting,'la mutation doit attendre le verrou du dossier');
    await lock.query("update briefs set responsable='Alice Recette' where id=$1",[b.id]); await lock.query('commit');
    assert.equal((await pending).status,403);
    assert.equal((await db.query('select projet from briefs where id=$1',[b.id])).rows[0].projet,b.projet);
  } finally {await lock.query('rollback');lock.release();}
});

test('les mêmes restrictions restent actives après redémarrage', async () => {
  const port=Number(new URL(origin).port); await stopChild(); await startChild(port);
  assert.deepEqual(await (await req('/rest/v1/briefs?ndeg=eq.ROLE-READ-FOREIGN','bob')).json(),[]);
  assert.equal((await req('/rest/v1/comments','bob','POST',{ndeg:'ROLE-COMMENT-OTHER',body:'Après boot'})).status,403);
  assert.equal((await (await req('/rest/v1/task_events?ndeg=eq.ROLE-HISTORY-OWN','bob')).json()).length,2);
});

test('les variantes encodées ne contournent pas le portail RH', async () => {
  for(const route of ['/rh%2fevaluation-departement.html','/stub%2f..%2frh%2fevaluation-departement.html']) {
    assert.equal((await req(route,'bob')).status,403,route);
    assert.equal((await req(route,'sue')).status,403,route);
  }
  assert.equal((await req('/rh%2fevaluation-departement.html','alice')).status,200);
});

test('un ancien fichier de données placé dans briefs ne devient pas une API parallèle', async () => {
  for (const ext of ['csv','json','md','sql']) {
    const filename='recette-donnees-'+process.pid+'.'+ext;
    const file=new URL('../briefs/'+filename,import.meta.url);
    await writeFile(file,'CONTENU_BRUT_INTERDIT',{flag:'wx'});
    try {
      assert.equal((await req('/'+filename,'alice')).status,404);
      assert.equal((await req('/'+filename,'bob')).status,404);
    } finally {await rm(file);}
  }
});

test('le mois autorisé vient du serveur et les événements sans qualification de rôle sont signalés', async () => {
  assert.equal((await (await req('/profil','bob')).json()).taskMonth,currentDeadline().slice(0,7));
  const r=await req('/rest/v1/task_events?ndeg=eq.ROLE-HISTORY-OWN','bob');
  assert.equal(r.headers.get('x-radar-unqualified-role-events'),'1');
});

test('les imports concurrents allouent des codes distincts sans exposer le portefeuille complet', async () => {
  const responses=await Promise.all([1,2,3].map(n=>req('/ingest','bob','POST',{text:'Retour parallèle '+n,client:'Recette'})));
  for(const r of responses) assert.equal(r.status,201);
  const results=await Promise.all(responses.map(r=>r.json()));
  const codes=results.map(r=>r.created[0].ndeg); assert.equal(new Set(codes).size,3);
  const count=await db.query('select count(*)::int as n from briefs where ndeg=any($1)',[codes]); assert.equal(count.rows[0].n,3);
});

test('la réutilisation d’un code ne transfère pas les médias ou commentaires du dossier supprimé', async () => {
  const b=await fixture('ROLE-REUSE');
  const asset=await (await req('/visuels','bob','POST',{ndeg:b.ndeg,data:png})).json();
  const comment=await (await req('/rest/v1/comments','bob','POST',{ndeg:b.ndeg,body:'ANCIEN_COMMENTAIRE'})).json();
  await db.query('delete from briefs where id=$1',[b.id]);
  await fixture('ROLE-REUSE',{responsable:'Alice Recette'});
  assert.equal((await req('/visuels/'+asset.filename,'alice')).status,404);
  assert.deepEqual(await (await req('/rest/v1/brief_assets?id=eq.'+asset.id,'alice')).json(),[]);
  assert.deepEqual(await (await req('/rest/v1/comments?id=eq.'+comment[0].id,'alice')).json(),[]);
});

test('le changement de code conserve les liens qualifiés et le client ne peut imposer un identifiant parent', async () => {
  const b=await fixture('ROLE-RENAME');
  const a=await (await req('/visuels','bob','POST',{ndeg:b.ndeg,data:png})).json();
  const c=(await (await req('/rest/v1/comments','bob','POST',{ndeg:b.ndeg,body:'Suivi'})).json())[0];
  assert.equal(a.brief_id,b.id); assert.equal(c.brief_id,b.id);
  assert.equal((await req('/rest/v1/comments','bob','POST',{ndeg:b.ndeg,brief_id:1,body:'Faux parent'})).status,400);
  assert.equal((await req('/rest/v1/comments?id=eq.'+c.id,'bob','PATCH',{brief_id:1})).status,400);
  assert.equal((await req('/rest/v1/briefs?id=eq.'+b.id,'bob','PATCH',{ndeg:'ROLE-RENAMED'})).status,200);
  assert.equal((await (await req('/rest/v1/comments?ndeg=eq.ROLE-RENAMED','bob')).json())[0].id,c.id);
  assert.equal((await (await req('/rest/v1/brief_assets?ndeg=eq.ROLE-RENAMED','bob')).json())[0].id,a.id);
  assert.equal((await req('/visuels/'+a.filename,'bob')).status,200);
  // Ancien rattachement non prouvé : aucune migration n'en invente l'origine.
  await db.query("insert into comments(ndeg,body) values ('ROLE-RENAMED','ANCIEN_SANS_ID')");
  const migration=await readFile(new URL('../server/journal.sql',import.meta.url),'utf8'); await db.query(migration);
  assert.equal((await db.query("select brief_id from comments where body='ANCIEN_SANS_ID'")).rows[0].brief_id,null);
  assert.equal((await (await req('/rest/v1/comments?ndeg=eq.ROLE-RENAMED','bob')).json()).length,1);
});
