-- Visuels de livrables : métadonnées des images attachées aux briefs.
-- Miroir documentaire de SCHEMA_SQL (server/pgrest.js) — le serveur crée cette
-- table tout seul au boot ; ce fichier sert aux bases gérées à la main.
-- Les binaires vivent sur le volume persistant (VISUELS_DIR, défaut /data/visuels) ;
-- création/suppression passent par POST/DELETE /visuels (jamais par le REST direct).
create table if not exists brief_assets (
  id bigint generated by default as identity primary key,
  ndeg text not null, client text, projet text,
  filename text not null, mime text, bytes int8, caption text,
  created_by text, created_at timestamptz default now()
);
create index if not exists brief_assets_ndeg_idx on brief_assets (ndeg);
create index if not exists brief_assets_at_idx on brief_assets (created_at desc);
