// ============================================================
//  RADAR — mini-PostgREST maison (Node + Postgres)
//  Le front parle PostgREST brut (fetch sur /rest/v1/<table>?<query>). Ici on
//  sert EXACTEMENT le sous-ensemble utilisé — select/order/limit, filtres
//  eq/neq/cs/in/gte/lte/is, INSERT/PATCH/DELETE — traduit en SQL paramétré
//  contre la base `radar`.
//  Sécurité : tables + colonnes en liste blanche (jamais d'identifiant venant du
//  client dans le SQL sans validation), valeurs toujours en $n. Isolation
//  private_to appliquée côté serveur (même pour owner) — la confidentialité ne
//  dépend plus du filtre d'UI. Journal task_events émis à chaque écriture de brief.
// ============================================================
"use strict";
import pg from "pg";
import { readFileSync } from "node:fs";
import { assertBriefAccess, briefScopeSql, taskAuthority } from "../functions/_authz.js";

const { Pool } = pg;
const pool = process.env.DATABASE_URL
  ? new Pool({ connectionString: process.env.DATABASE_URL, max: 6, idleTimeoutMillis: 30000 })
  : null;
export const hasDb = () => !!pool;

// ---- métadonnées des tables (liste blanche) --------------------------------
const TEXT = "text", TS = "timestamptz", BOOL = "boolean", JSONB = "jsonb", INT = "int8", ARR = "text[]";
const BRIEFS_COLS = {
  id: "id", categorie: TEXT, closed_at: TS, ndeg: TEXT, client: TEXT, marque: TEXT, cluster: TEXT,
  pays: TEXT, projet: TEXT, niveau: TEXT, type: TEXT, statut: TEXT, prio: TEXT, avancement: TEXT,
  deadline: TEXT, responsable: TEXT, livrables: TEXT, date_reception: TEXT, thread_id: TEXT,
  entree: TEXT, parent: TEXT, comm: TEXT, entre_par: TEXT, doc_brief: TEXT, doc_propal: TEXT,
  doc_livr: TEXT, depends_on: TEXT, created_at: TS, updated_at: TS, brief_etat: TEXT,
  classif_inferee: BOOL, deadline_hard: BOOL, brief_client: JSONB, brief_creatif: JSONB,
  brief_production: JSONB, case_study: JSONB, suivi: JSONB, private_to: TEXT,
};
const TABLES = {
  briefs: { pk: "id", cols: BRIEFS_COLS },
  clients: { pk: "id", cols: { id: "id", ordre: INT, nom: TEXT, client: TEXT, data: JSONB, updated_at: TS } },
  client_markets: { pk: "id", cols: { id: "id", client: TEXT, data: JSONB, updated_at: TS } },
  client_contacts: { pk: "id", cols: { id: "id", client: TEXT, data: JSONB, updated_at: TS } },
  comments: { pk: "id", cols: { id: "id", brief_id: "id", ndeg: TEXT, author: TEXT, involved: ARR, body: TEXT, kind: TEXT, created_at: TS } },
  app_config: { pk: "key", cols: { key: TEXT, value: JSONB } },
  task_events: { pk: "id", readOnly: true, cols: {
    brief_id: "id", private_to: TEXT,
    id: "id", at: TS, ndeg: TEXT, entree: TEXT, client: TEXT, projet: TEXT, kind: TEXT,
    statut_old: TEXT, statut_new: TEXT, resp_old: TEXT, resp_new: TEXT, summary: TEXT } },
  // Visuels de livrables. Lecture (et PATCH de caption) via REST ; création et
  // suppression UNIQUEMENT via /visuels (le fichier disque vit et meurt avec la ligne).
  brief_assets: { pk: "id", noRestWrite: true, patchCols: ['caption'], cols: {
    id: "id", brief_id: "id", ndeg: TEXT, client: TEXT, projet: TEXT, filename: TEXT, mime: TEXT,
    bytes: INT, caption: TEXT, created_by: TEXT, created_at: TS } },
};
const isCol = (t, c) => Object.prototype.hasOwnProperty.call(TABLES[t].cols, c);
const colType = (t, c) => TABLES[t].cols[c];

// ---- schéma (idempotent) ---------------------------------------------------
const SCHEMA_SQL = `
create table if not exists briefs (
  id bigint generated by default as identity primary key,
  categorie text, closed_at timestamptz, ndeg text, client text, marque text, cluster text,
  pays text, projet text, niveau text, type text, statut text, prio text, avancement text,
  deadline text, responsable text, livrables text, date_reception text, thread_id text,
  entree text, parent text, comm text, entre_par text, doc_brief text, doc_propal text,
  doc_livr text, depends_on text, created_at timestamptz default now(), updated_at timestamptz default now(),
  brief_etat text, classif_inferee boolean default false, deadline_hard boolean default false,
  brief_client jsonb, brief_creatif jsonb, brief_production jsonb, case_study jsonb, suivi jsonb,
  private_to text
);
create index if not exists briefs_ndeg_idx on briefs (ndeg);
create table if not exists clients (
  id bigint generated by default as identity primary key,
  ordre int default 0, nom text, client text, data jsonb, updated_at timestamptz default now()
);
create table if not exists client_markets (
  id bigint generated by default as identity primary key, client text, data jsonb, updated_at timestamptz default now()
);
create table if not exists client_contacts (
  id bigint generated by default as identity primary key, client text, data jsonb, updated_at timestamptz default now()
);
create table if not exists comments (
  id bigint generated by default as identity primary key,
  ndeg text, author text, involved text[] default '{}', body text, kind text, created_at timestamptz default now()
);
create table if not exists app_config ( key text primary key, value jsonb );
create table if not exists task_events (
  id bigint generated by default as identity primary key,
  at timestamptz default now(), ndeg text, entree text, client text, projet text, kind text,
  statut_old text, statut_new text, resp_old text, resp_new text, summary text
);
create index if not exists task_events_at_idx on task_events (at desc);
create table if not exists brief_assets (
  id bigint generated by default as identity primary key,
  ndeg text not null, client text, projet text,
  filename text not null, mime text, bytes int8, caption text,
  created_by text, created_at timestamptz default now()
);
create index if not exists brief_assets_ndeg_idx on brief_assets (ndeg);
create index if not exists brief_assets_at_idx on brief_assets (created_at desc);
`;

// ---- CSV (repli de seed) : même colonnes que INDEX.csv ---------------------
function parseCSV(t) {
  t = t.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  const rows = []; let i = 0, f = "", row = [], q = false;
  while (i < t.length) {
    const c = t[i];
    if (q) { if (c === '"') { if (t[i + 1] === '"') { f += '"'; i += 2; continue; } q = false; i++; continue; } f += c; i++; continue; }
    if (c === '"') { q = true; i++; continue; }
    if (c === ",") { row.push(f); f = ""; i++; continue; }
    if (c === "\n") { row.push(f); rows.push(row); row = []; f = ""; i++; continue; }
    f += c; i++;
  }
  if (f.length || row.length) { row.push(f); rows.push(row); }
  return rows;
}
const CSV_MAP = {
  "N°": "ndeg", "Client": "client", "Marque": "marque", "Cluster": "cluster", "Pays": "pays",
  "Projet": "projet", "Niveau": "niveau", "Type": "type", "Statut": "statut", "Priorité": "prio",
  "Avancement": "avancement", "Deadline": "deadline", "Responsable": "responsable", "Livrables": "livrables",
  "Date réception": "date_reception", "threadId": "thread_id", "Type entrée": "entree",
  "Rattaché à": "parent", "Commentaires": "comm", "Doc-Brief": "doc_brief", "Doc-Propal": "doc_propal",
  "Doc-Livr": "doc_livr", "Entré par": "entre_par",
};
async function seedFromCsv(client, csvPath) {
  let text;
  try { text = readFileSync(csvPath, "utf8"); }
  catch (e) { console.warn(`[pgrest] RADAR_SEED_CSV illisible (${csvPath}) — seed sauté:`, e && e.message); return 0; }
  const rows = parseCSV(text);
  if (rows.length < 2) return 0;
  const header = rows[0].map((x) => x.trim());
  const cols = header.map((h) => CSV_MAP[h] || null);
  let n = 0;
  for (let r = 1; r < rows.length; r++) {
    const cells = rows[r];
    if (!cells || !cells.length) continue;
    const rec = {};
    header.forEach((h, ci) => { const dbcol = cols[ci]; if (dbcol) rec[dbcol] = (cells[ci] || "").trim(); });
    if (!rec.ndeg) continue;
    const keys = Object.keys(rec);
    const ph = keys.map((_, k) => "$" + (k + 1)).join(",");
    await client.query(`insert into briefs (${keys.join(",")}) values (${ph})`, keys.map((k) => rec[k]));
    n++;
  }
  return n;
}

// ---- init : schéma + seed si vide ------------------------------------------
let _ready = null;
export function initDb() {
  if (!pool) return Promise.resolve(false);
  if (_ready) return _ready;
  _ready = (async () => {
    const client = await pool.connect();
    try {
      await client.query("begin");
      await client.query(SCHEMA_SQL);
      await client.query(readFileSync(new URL('./journal.sql', import.meta.url), 'utf8'));
      const { rows } = await client.query("select count(*)::int as n from briefs");
      // RADAR_SEED_CSV = chemin d'un CSV optionnel (colonnes INDEX.csv) pour peupler une
      // base vide au premier boot. Absent → instance vierge, aucune dépendance à un dossier local.
      const csvPath = process.env.RADAR_SEED_CSV;
      if (rows[0].n === 0 && csvPath) {
        const seeded = await seedFromCsv(client, csvPath);
        console.log(`[pgrest] schéma prêt · briefs vides → ${seeded} lignes semées depuis ${csvPath}`);
      } else {
        console.log(`[pgrest] schéma prêt · ${rows[0].n} briefs en base${!csvPath ? " (RADAR_SEED_CSV non défini)" : ""}`);
      }
      await client.query("commit");
      return true;
    } catch (e) {
      try { await client.query("rollback"); } catch {}
      console.error("[pgrest] initDb échec:", e && e.message);
      return false;
    } finally { client.release(); }
  })();
  return _ready;
}

// ---- parsing PostgREST -----------------------------------------------------
const json = (obj, status = 200, extra) => new Response(JSON.stringify(obj), {
  status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", ...(extra || {}) },
});
// un filtre PostgREST : valeur = "<op>.<reste>"
function buildFilter(table, col, raw, params) {
  const dot = raw.indexOf(".");
  const op = dot >= 0 ? raw.slice(0, dot) : "eq";
  let val = dot >= 0 ? raw.slice(dot + 1) : raw;
  const type = colType(table, col);
  const P = (v) => { params.push(v); return "$" + params.length; };
  switch (op) {
    case "eq": return `${col} = ${P(coerce(type, val))}`;
    case "neq": return `${col} <> ${P(coerce(type, val))}`;
    case "gte": return `${col} >= ${P(coerce(type, val))}`;
    case "lte": return `${col} <= ${P(coerce(type, val))}`;
    case "gt": return `${col} > ${P(coerce(type, val))}`;
    case "lt": return `${col} < ${P(coerce(type, val))}`;
    case "like": return `${col} like ${P(val)}`;
    case "ilike": return `${col} ilike ${P(val)}`;
    case "is": return `${col} is ${/^null$/i.test(val) ? "null" : /^true$/i.test(val) ? "true" : "false"}`;
    case "in": { // in.(a,b,c)
      const inner = val.replace(/^\(/, "").replace(/\)$/, "");
      const items = inner.length ? inner.split(",").map((s) => s.replace(/^"|"$/g, "")) : [];
      return `${col} = any(${P(items.map((v) => coerce(type, v)))})`;
    }
    case "cs": return `${col} @> ${P(val)}::${type === ARR ? "text[]" : "jsonb"}`; // contains (array/jsonb)
    default: return `${col} = ${P(coerce(type, val))}`;
  }
}
function coerce(type, v) {
  if (v === "" && type !== TEXT) return null;
  if (type === BOOL) return /^true$/i.test(v);
  if (type === INT || type === "id") return v === "" ? null : Number(v);
  return v; // text / timestamptz (chaîne acceptée par PG)
}
function paramForWrite(type, v) {
  if (v == null) return null;
  if (type === JSONB) return typeof v === "string" ? v : JSON.stringify(v);
  if (type === ARR) return Array.isArray(v) ? v : (typeof v === "string" ? v : [v]);
  return v;
}

// ---- scope private_to (confidentialité serveur, tous rôles) ----------------
export async function targetBrief(client, ndeg, context) {
  const { rows } = await client.query('select * from briefs where ndeg=$1 order by id for share', [ndeg]);
  if (!rows.length) throw Object.assign(new Error('brief inconnu'),{status:404});
  if (rows.length !== 1) throw Object.assign(new Error('code de brief ambigu : rattachement à qualifier'),{status:409});
  assertBriefAccess(rows[0],context);
  return rows[0];
}

export function linkedBriefJoin(table) {
  return `((${table}.brief_id is not null and b.id=${table}.brief_id) or (${table}.brief_id is null and b.ndeg=${table}.ndeg))`;
}
export async function targetLinkedBrief(client,row,context) {
  if (row.brief_id == null) {
    const who=taskAuthority(context);
    if (!who.fullAccess && !['owner','supervisor'].includes(who.role))
      throw Object.assign(new Error('ancien rattachement à qualifier'),{status:403});
    return targetBrief(client,row.ndeg,context);
  }
  const {rows}=await client.query('select * from briefs where id=$1 for share',[row.brief_id]);
  if (!rows.length) throw Object.assign(new Error('dossier rattaché introuvable'),{status:404});
  assertBriefAccess(rows[0],context);
  return rows[0];
}

// ---- émission d'un événement de journal (task_events) ----------------------
// Le média et sa trace partagent la transaction et le brief verrouillé.
export async function emitEvent(client, ev, brief) {
  if (!brief?.id) throw new Error('rattachement de journal non qualifié');
  const cols = ["brief_id", "private_to", "scope_snapshot", "ndeg", "entree", "client", "projet", "kind", "statut_old", "statut_new", "resp_old", "resp_new", "summary"];
  ev = { ...ev, brief_id: brief.id, private_to: brief.private_to || '', scope_snapshot: JSON.stringify({
    private_to: brief.private_to || '', responsable:brief.responsable, deadline:brief.deadline, statut:brief.statut, closed_at:brief.closed_at,
  }) };
  const vals = cols.map((c) => ev[c] ?? null);
  const ph = cols.map((_, i) => "$" + (i + 1)).join(",");
  await client.query(`insert into task_events (${cols.join(",")}) values (${ph})`, vals);
}

export async function transaction(work) {
  const client = await pool.connect();
  try { await client.query('begin'); const result = await work(client); await client.query('commit'); return result; }
  catch (e) { await client.query('rollback').catch(() => {}); throw e; }
  finally { client.release(); }
}
// ---- handler principal : /rest/v1/<table> ----------------------------------
export async function handleRest(context) {
  if (!pool) return json({ message: "base non configurée" }, 503);
  if (!await initDb()) return json({ message: "base indisponible" }, 503);
  const { request } = context;
  const url = new URL(request.url);
  const table = decodeURIComponent(url.pathname.replace(/^\/rest\/v1\//, "").split("/")[0].split("?")[0]);
  if (!TABLES[table]) return json({ message: "table inconnue: " + table }, 404);
  const email = (context.data && context.data.email) || "";
  const method = request.method.toUpperCase();
  if (TABLES[table].readOnly && method !== 'GET') return json({ message: 'journal en lecture seule' }, 405);
  // brief_assets : créer/supprimer passe par /visuels (sinon fichiers disque orphelins).
  if (TABLES[table].noRestWrite && (method === "POST" || method === "DELETE"))
    return json({ message: "utiliser POST/DELETE /visuels pour cette table" }, 405);
  const wantRepr = (request.headers.get("Prefer") || "").includes("return=representation");

  // colonnes demandées (select)
  const selRaw = url.searchParams.get("select");
  let selectCols = "*";
  if (selRaw && selRaw !== "*") {
    const wanted = selRaw.split(",").map((s) => s.trim().split(":").pop());
    for (const c of wanted) if (!isCol(table, c)) return json({ message: "colonne inconnue: " + c }, 400);
    selectCols = wanted.join(",");
  }

  // filtres (tous les params sauf mots réservés)
  const RESERVED = new Set(["select", "order", "limit", "offset"]);
  const params = [];
  const where = [];
  for (const [k, v] of url.searchParams) {
    if (RESERVED.has(k)) continue;
    if (!isCol(table, k)) return json({ message: "filtre sur colonne inconnue: " + k }, 400);
    where.push(buildFilter(table, k, v, params));
  }
  const hasUserFilter = where.length > 0;
  // Les mutations verrouillent tous les candidats : aucun lot partiel silencieux.
  if (method === 'GET' && table === 'briefs') where.push(briefScopeSql(context,params));
  if (method === 'GET' && (table === 'brief_assets' || table === 'comments')) {
    const who=taskAuthority(context);
    if (!who.fullAccess && !['owner','supervisor'].includes(who.role)) where.push(`${table}.brief_id is not null`);
    const join=linkedBriefJoin(table);
    where.push(`(select count(*) from briefs b where ${join}) = 1`);
    where.push(`exists (select 1 from briefs b where ${join} and ${briefScopeSql(context,params,'b.')})`);
  }
  if (table === 'task_events' && !context.data?.fullAccess) {
    const who = taskAuthority(context), me = who.person || '';
    params.push(me);
    where.push(`(private_to = '' or private_to = $${params.length})`);
    where.push(`not exists (select 1 from briefs b where b.id = task_events.brief_id and coalesce(b.private_to,'') <> '' and b.private_to <> $${params.length})`);
    where.push(`not exists (select 1 from task_events d where d.brief_id=task_events.brief_id and d.kind='deleted' and coalesce(d.private_to,'') <> '' and d.private_to <> $${params.length})`);
    if (who.role !== 'owner' && who.role !== 'supervisor') {
      const snapshotFields = alias => Object.fromEntries(['private_to','responsable','deadline','statut','closed_at'].map(k=>[k,`(${alias}.scope_snapshot->>'${k}')`]));
      where.push(`scope_snapshot is not null and ${briefScopeSql(context,params,snapshotFields('task_events'))}`);
      where.push(`(exists (select 1 from briefs b where b.id=task_events.brief_id and ${briefScopeSql(context,params,'b.')})
        or (not exists (select 1 from briefs b where b.id=task_events.brief_id)
          and exists (select 1 from task_events d where d.brief_id=task_events.brief_id and d.kind='deleted'
            and ${briefScopeSql(context,params,snapshotFields('d'))})))`);
    }
  }

  try {
    if (method === "GET") {
      let sql = `select ${selectCols} from ${table}`;
      if (where.length) sql += " where " + where.join(" and ");
      const ord = url.searchParams.get("order");
      if (ord) {
        const parts = ord.split(",").map((o) => {
          const [c, dir] = o.split(".");
          if (!isCol(table, c)) return null;
          return `${c} ${/desc/i.test(dir || "") ? "desc" : "asc"}`;
        }).filter(Boolean);
        if (parts.length) sql += " order by " + parts.join(",");
      }
      const lim = parseInt(url.searchParams.get("limit") || "", 10);
      if (Number.isFinite(lim)) sql += ` limit ${Math.min(Math.max(lim, 0), 10000)}`;
      const off = parseInt(url.searchParams.get("offset") || "", 10);
      if (Number.isFinite(off)) sql += ` offset ${Math.max(off, 0)}`;
      const { rows } = await pool.query(sql, params);
      const headers = {};
      if (table === 'task_events') {
        const unknown = await pool.query('select count(*)::int as n from task_events where private_to is null');
        headers['X-Radar-Unqualified-Events'] = String(unknown.rows[0].n);
        if (!context.data?.fullAccess && !['owner','supervisor'].includes(taskAuthority(context).role)) {
          const unqualified = await pool.query('select count(*)::int as n from task_events where private_to is not null and scope_snapshot is null');
          headers['X-Radar-Unqualified-Role-Events'] = String(unqualified.rows[0].n);
        }
      }
      return json(rows, 200, headers);
    }

    if (method === "POST") {
      let body = await request.json().catch(() => null);
      if (!body || typeof body !== 'object') return json({ message: "corps JSON attendu" }, 400);
      const list = Array.isArray(body) ? body : [body];
      if (!list.length) return json([]);
      if (list.some(rec => !rec || typeof rec !== 'object' || Array.isArray(rec)
        || !Object.keys(rec).some(k => isCol(table, k) && k !== 'id'))) return json({ message: 'aucune colonne reconnue à insérer' }, 400);
      const client = await pool.connect();
      try {
        await client.query("begin");
        const out = [];
        for (const rec of list) {
          if (table === 'briefs') assertBriefAccess(rec,context);
          if (table === 'comments') {
            if (Object.hasOwn(rec,'brief_id')) throw Object.assign(new Error('rattachement réservé au serveur'),{status:400});
            rec.brief_id=(await targetBrief(client,rec.ndeg,context)).id;
          }
          const keys = Object.keys(rec).filter((k) => isCol(table, k) && k !== "id");
          const vals = keys.map((k) => paramForWrite(colType(table, k), rec[k]));
          const ph = keys.map((_, i) => "$" + (i + 1)).join(",");
          const ret = wantRepr ? " returning *" : "";
          const q = keys.length
            ? `insert into ${table} (${keys.join(",")}) values (${ph})${ret}`
            : `insert into ${table} default values${ret}`;
          const res = await client.query(q, vals);
          if (res.rows[0]) out.push(res.rows[0]);
        }
        await client.query("commit");
        return json(wantRepr ? out : [], 201);
      } catch (e) { await client.query("rollback").catch(() => {}); throw e; }
      finally { client.release(); }
    }

    if (method === "PATCH" || method === "DELETE") {
      if (!hasUserFilter) return json({ message: "écriture sans filtre refusée" }, 400);
      const client = await pool.connect();
      try {
        await client.query("begin");
        const candidates = await client.query(`select * from ${table} where ${where.join(' and ')} order by ${TABLES[table].pk} for update`,params);
        if (!candidates.rows.length) { await client.query('rollback'); return json({message:'ligne introuvable'},404); }
        for (const row of candidates.rows) {
          if (table === 'briefs') assertBriefAccess(row,context);
          if (table === 'comments' || table === 'brief_assets') await targetLinkedBrief(client,row,context);
        }
        const ids = candidates.rows.map(row=>row[TABLES[table].pk]);
        const writeWhere = `${TABLES[table].pk} = any($1)`;
        let result;
        if (method === "DELETE") {
          result = await client.query(`delete from ${table} where ${writeWhere}${wantRepr ? " returning *" : ""}`, [ids]);
        } else {
          const body = await request.json().catch(() => ({}));
          const patch = body && typeof body === "object" ? body : {};
          if (table === 'comments') {
            if (Object.hasOwn(patch,'brief_id')) throw Object.assign(new Error('rattachement réservé au serveur'),{status:400});
            if (Object.hasOwn(patch,'ndeg')) patch.brief_id=(await targetBrief(client,patch.ndeg,context)).id;
          }
          if (TABLES[table].patchCols && Object.keys(patch).some(k => !TABLES[table].patchCols.includes(k))) {
            await client.query('rollback'); return json({ message: 'seule la légende du visuel est modifiable ici' }, 400);
          }
          const keys = Object.keys(patch).filter((k) => isCol(table, k) && k !== TABLES[table].pk);
          if (!keys.length) { await client.query("rollback"); return json({ message: "aucune colonne à modifier" }, 400); }
          // updated_at auto si la colonne existe
          if (isCol(table, "updated_at") && !keys.includes("updated_at")) { patch.updated_at = new Date().toISOString(); keys.push("updated_at"); }
          const setParams = [ids]; // Écrit exactement les candidats reçus sous verrou.
          const sets = keys.map((k) => { setParams.push(paramForWrite(colType(table, k), patch[k])); return `${k} = $${setParams.length}`; });
          result = await client.query(`update ${table} set ${sets.join(",")} where ${writeWhere}${wantRepr ? " returning *" : ""}`, setParams);
          if (table === 'briefs' && keys.includes('ndeg')) {
            for (const linked of ['comments','brief_assets'])
              await client.query(`update ${linked} set ndeg=$1 where brief_id=any($2)`,[patch.ndeg,ids]);
          }
        }
        await client.query("commit");
        return json(wantRepr ? (result.rows || []) : []);
      } catch (e) { await client.query("rollback").catch(() => {}); throw e; }
      finally { client.release(); }
    }

    return json({ message: "méthode non supportée" }, 405);
  } catch (e) {
    if (e.status) return json({message:e.message},e.status);
    console.error("[pgrest]", method, table, e && e.message);
    return json({ message: "erreur SQL", detail: String((e && e.message) || e) }, 500);
  }
}
// ---- lecture directe (pour _feed.js côté serveur) --------------------------
export async function query(sql, params) {
  if (!pool) throw new Error("no db");
  return pool.query(sql, params);
}

// Repli historique de supa.js : même source et même autorité que REST.
// Un INDEX.csv déposé sur disque n'est jamais une seconde base lisible brute.
export async function handleBriefCsv(context) {
  if (!pool || !await initDb()) return json({message:'base indisponible'},503);
  const params=[], scope=briefScopeSql(context,params);
  const {rows}=await pool.query(`select * from briefs where ${scope} order by ndeg`,params);
  const entries=Object.entries(CSV_MAP);
  const cell=value=>'"'+String(value ?? '').replaceAll('"','""')+'"';
  const csv=[entries.map(([label])=>cell(label)).join(','),
    ...rows.map(row=>entries.map(([,key])=>cell(row[key])).join(','))].join('\r\n')+'\r\n';
  return new Response(csv,{headers:{'Content-Type':'text/csv; charset=utf-8','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
}
