// ============================================================
//  Matanga RADAR — mini-PostgREST maison (Node + Postgres Coolify)
//  Remplace le backend Supabase : le front (briefs/*.js) parle déjà PostgREST
//  brut (fetch sur /rest/v1/<table>?<query>). Ici on sert EXACTEMENT le
//  sous-ensemble utilisé — select/order/limit, filtres eq/neq/cs/in/gte/lte/is,
//  INSERT/PATCH/DELETE — traduit en SQL paramétré contre la base `radar`.
//  Sécurité : tables + colonnes en liste blanche (jamais d'identifiant venant du
//  client dans le SQL sans validation), valeurs toujours en $n. Isolation
//  private_to appliquée côté serveur (même pour owner) — la confidentialité ne
//  dépend plus du filtre d'UI. Journal task_events émis à chaque écriture de brief.
// ============================================================
"use strict";
import pg from "pg";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { identityFor } from "../functions/_authz.js";

const { Pool } = pg;
const ROOT = dirname(fileURLToPath(import.meta.url));
const pool = process.env.DATABASE_URL
  ? new Pool({ connectionString: process.env.DATABASE_URL, max: 6, idleTimeoutMillis: 30000 })
  : null;
export const hasDb = () => !!pool;

// ---- métadonnées des tables (liste blanche) --------------------------------
const TEXT = "text", TS = "timestamptz", BOOL = "boolean", JSONB = "jsonb", INT = "int8", ARR = "text[]";
const BRIEFS_COLS = {
  id: "id", categorie: TEXT, closed_at: TS, ndeg: TEXT, client: TEXT, marque: TEXT, cluster: TEXT,
  pays: TEXT, projet: TEXT, niveau: TEXT, type: TEXT, statut: TEXT, prio: TEXT, avancement: TEXT,
  deadline: TEXT, responsable: TEXT, livrables: TEXT, date_reception: TEXT, thread_id: TEXT,
  entree: TEXT, parent: TEXT, comm: TEXT, entre_par: TEXT, doc_brief: TEXT, doc_propal: TEXT,
  doc_livr: TEXT, depends_on: TEXT, created_at: TS, updated_at: TS, brief_etat: TEXT,
  classif_inferee: BOOL, deadline_hard: BOOL, brief_client: JSONB, brief_creatif: JSONB,
  brief_production: JSONB, case_study: JSONB, suivi: JSONB, private_to: TEXT,
};
const TABLES = {
  briefs: { pk: "id", cols: BRIEFS_COLS },
  clients: { pk: "id", cols: { id: "id", ordre: INT, nom: TEXT, client: TEXT, data: JSONB, updated_at: TS } },
  client_markets: { pk: "id", cols: { id: "id", client: TEXT, data: JSONB, updated_at: TS } },
  client_contacts: { pk: "id", cols: { id: "id", client: TEXT, data: JSONB, updated_at: TS } },
  comments: { pk: "id", cols: { id: "id", ndeg: TEXT, author: TEXT, involved: ARR, body: TEXT, kind: TEXT, created_at: TS } },
  app_config: { pk: "key", cols: { key: TEXT, value: JSONB } },
  task_events: { pk: "id", cols: {
    id: "id", at: TS, ndeg: TEXT, entree: TEXT, client: TEXT, projet: TEXT, kind: TEXT,
    statut_old: TEXT, statut_new: TEXT, resp_old: TEXT, resp_new: TEXT, summary: TEXT } },
};
const isCol = (t, c) => Object.prototype.hasOwnProperty.call(TABLES[t].cols, c);
const colType = (t, c) => TABLES[t].cols[c];

// ---- schéma (idempotent) ---------------------------------------------------
const SCHEMA_SQL = `
create table if not exists briefs (
  id bigint generated by default as identity primary key,
  categorie text, closed_at timestamptz, ndeg text, client text, marque text, cluster text,
  pays text, projet text, niveau text, type text, statut text, prio text, avancement text,
  deadline text, responsable text, livrables text, date_reception text, thread_id text,
  entree text, parent text, comm text, entre_par text, doc_brief text, doc_propal text,
  doc_livr text, depends_on text, created_at timestamptz default now(), updated_at timestamptz default now(),
  brief_etat text, classif_inferee boolean default false, deadline_hard boolean default false,
  brief_client jsonb, brief_creatif jsonb, brief_production jsonb, case_study jsonb, suivi jsonb,
  private_to text
);
create index if not exists briefs_ndeg_idx on briefs (ndeg);
create table if not exists clients (
  id bigint generated by default as identity primary key,
  ordre int default 0, nom text, client text, data jsonb, updated_at timestamptz default now()
);
create table if not exists client_markets (
  id bigint generated by default as identity primary key, client text, data jsonb, updated_at timestamptz default now()
);
create table if not exists client_contacts (
  id bigint generated by default as identity primary key, client text, data jsonb, updated_at timestamptz default now()
);
create table if not exists comments (
  id bigint generated by default as identity primary key,
  ndeg text, author text, involved text[] default '{}', body text, kind text, created_at timestamptz default now()
);
create table if not exists app_config ( key text primary key, value jsonb );
create table if not exists task_events (
  id bigint generated by default as identity primary key,
  at timestamptz default now(), ndeg text, entree text, client text, projet text, kind text,
  statut_old text, statut_new text, resp_old text, resp_new text, summary text
);
create index if not exists task_events_at_idx on task_events (at desc);
`;

// ---- CSV (repli de seed) : même colonnes que INDEX.csv ---------------------
function parseCSV(t) {
  t = t.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  const rows = []; let i = 0, f = "", row = [], q = false;
  while (i < t.length) {
    const c = t[i];
    if (q) { if (c === '"') { if (t[i + 1] === '"') { f += '"'; i += 2; continue; } q = false; i++; continue; } f += c; i++; continue; }
    if (c === '"') { q = true; i++; continue; }
    if (c === ",") { row.push(f); f = ""; i++; continue; }
    if (c === "\n") { row.push(f); rows.push(row); row = []; f = ""; i++; continue; }
    f += c; i++;
  }
  if (f.length || row.length) { row.push(f); rows.push(row); }
  return rows;
}
const CSV_MAP = {
  "N°": "ndeg", "Client": "client", "Marque": "marque", "Cluster": "cluster", "Pays": "pays",
  "Projet": "projet", "Niveau": "niveau", "Type": "type", "Statut": "statut", "Priorité": "prio",
  "Avancement": "avancement", "Deadline": "deadline", "Responsable": "responsable", "Livrables": "livrables",
  "Date réception": "date_reception", "threadId": "thread_id", "Type entrée": "entree",
  "Rattaché à": "parent", "Commentaires": "comm", "Doc-Brief": "doc_brief", "Doc-Propal": "doc_propal",
  "Doc-Livr": "doc_livr", "Entré par": "entre_par",
};
async function seedFromCsv(client) {
  let text;
  try { text = readFileSync(join(ROOT, "..", "briefs", "INDEX.csv"), "utf8"); }
  catch { console.warn("[pgrest] INDEX.csv introuvable — seed sauté"); return 0; }
  const rows = parseCSV(text);
  if (rows.length < 2) return 0;
  const header = rows[0].map((x) => x.trim());
  const cols = header.map((h) => CSV_MAP[h] || null);
  let n = 0;
  for (let r = 1; r < rows.length; r++) {
    const cells = rows[r];
    if (!cells || !cells.length) continue;
    const rec = {};
    header.forEach((h, ci) => { const dbcol = cols[ci]; if (dbcol) rec[dbcol] = (cells[ci] || "").trim(); });
    if (!rec.ndeg) continue;
    const keys = Object.keys(rec);
    const ph = keys.map((_, k) => "$" + (k + 1)).join(",");
    await client.query(`insert into briefs (${keys.join(",")}) values (${ph})`, keys.map((k) => rec[k]));
    n++;
  }
  return n;
}

// ---- init : schéma + seed si vide ------------------------------------------
let _ready = null;
export function initDb() {
  if (!pool) return Promise.resolve(false);
  if (_ready) return _ready;
  _ready = (async () => {
    const client = await pool.connect();
    try {
      await client.query(SCHEMA_SQL);
      const { rows } = await client.query("select count(*)::int as n from briefs");
      // SEED_BRIEFS=false → instance vierge (radar perso). Défaut true : préserve le radar Matanga.
      const doSeed = process.env.SEED_BRIEFS !== "false";
      if (rows[0].n === 0 && doSeed) {
        await client.query("begin");
        const seeded = await seedFromCsv(client);
        await client.query("commit");
        console.log(`[pgrest] schéma prêt · briefs vides → ${seeded} lignes semées depuis INDEX.csv`);
      } else {
        console.log(`[pgrest] schéma prêt · ${rows[0].n} briefs en base${!doSeed ? " (seed désactivé)" : ""}`);
      }
      return true;
    } catch (e) {
      try { await client.query("rollback"); } catch {}
      console.error("[pgrest] initDb échec:", e && e.message);
      return false;
    } finally { client.release(); }
  })();
  return _ready;
}

// ---- parsing PostgREST -----------------------------------------------------
const json = (obj, status = 200, extra) => new Response(JSON.stringify(obj), {
  status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", ...(extra || {}) },
});
// un filtre PostgREST : valeur = "<op>.<reste>"
function buildFilter(table, col, raw, params) {
  const dot = raw.indexOf(".");
  const op = dot >= 0 ? raw.slice(0, dot) : "eq";
  let val = dot >= 0 ? raw.slice(dot + 1) : raw;
  const type = colType(table, col);
  const P = (v) => { params.push(v); return "$" + params.length; };
  switch (op) {
    case "eq": return `${col} = ${P(coerce(type, val))}`;
    case "neq": return `${col} <> ${P(coerce(type, val))}`;
    case "gte": return `${col} >= ${P(coerce(type, val))}`;
    case "lte": return `${col} <= ${P(coerce(type, val))}`;
    case "gt": return `${col} > ${P(coerce(type, val))}`;
    case "lt": return `${col} < ${P(coerce(type, val))}`;
    case "like": return `${col} like ${P(val)}`;
    case "ilike": return `${col} ilike ${P(val)}`;
    case "is": return `${col} is ${/^null$/i.test(val) ? "null" : /^true$/i.test(val) ? "true" : "false"}`;
    case "in": { // in.(a,b,c)
      const inner = val.replace(/^\(/, "").replace(/\)$/, "");
      const items = inner.length ? inner.split(",").map((s) => s.replace(/^"|"$/g, "")) : [];
      return `${col} = any(${P(items.map((v) => coerce(type, v)))})`;
    }
    case "cs": return `${col} @> ${P(val)}::${type === ARR ? "text[]" : "jsonb"}`; // contains (array/jsonb)
    default: return `${col} = ${P(coerce(type, val))}`;
  }
}
function coerce(type, v) {
  if (v === "" && type !== TEXT) return null;
  if (type === BOOL) return /^true$/i.test(v);
  if (type === INT || type === "id") return v === "" ? null : Number(v);
  return v; // text / timestamptz (chaîne acceptée par PG)
}
function paramForWrite(type, v) {
  if (v == null) return null;
  if (type === JSONB) return typeof v === "string" ? v : JSON.stringify(v);
  if (type === ARR) return Array.isArray(v) ? v : (typeof v === "string" ? v : [v]);
  return v;
}

// ---- scope private_to (confidentialité serveur, tous rôles) ----------------
function briefsScope(email, params) {
  const me = identityFor(email || "").person || "";
  params.push(me);
  return `(private_to is null or private_to = '' or private_to = $${params.length})`;
}

// ---- émission d'un événement de journal (task_events) ----------------------
async function emitEvent(client, ev) {
  const cols = ["ndeg", "entree", "client", "projet", "kind", "statut_old", "statut_new", "resp_old", "resp_new", "summary"];
  const vals = cols.map((c) => ev[c] ?? null);
  const ph = cols.map((_, i) => "$" + (i + 1)).join(",");
  try { await client.query(`insert into task_events (${cols.join(",")}) values (${ph})`, vals); }
  catch (e) { console.warn("[pgrest] task_events KO:", e && e.message); }
}
const CLOSED = new Set(["Livré", "Livre", "Closed", "Clôturé", "Cloture", "Terminé", "Termine"]);
function kindFromChange(oldRow, patch) {
  const ns = patch.statut, os = oldRow.statut;
  if (ns != null && ns !== os) {
    if (ns === "Frozen") return { kind: "frozen", summary: "Tâche gelée" };
    if (os === "Frozen") return { kind: "unfrozen", summary: "Tâche réactivée" };
    if (CLOSED.has(ns)) return { kind: "closed", summary: "Clôturé : " + ns };
    if (CLOSED.has(os)) return { kind: "reopened", summary: "Rouvert : " + ns };
    return { kind: "status", summary: `${os || "—"} → ${ns}` };
  }
  if (patch.responsable != null && patch.responsable !== oldRow.responsable)
    return { kind: "reassigned", summary: `${oldRow.responsable || "—"} → ${patch.responsable}` };
  if (patch.deadline != null && patch.deadline !== oldRow.deadline)
    return { kind: "deadline", summary: `Échéance → ${patch.deadline || "—"}` };
  return null;
}

// ---- handler principal : /rest/v1/<table> ----------------------------------
export async function handleRest(context) {
  if (!pool) return json({ message: "base non configurée" }, 503);
  await initDb(); // idempotent + mémoïsé : garantit schéma prêt avant toute requête
  const { request } = context;
  const url = new URL(request.url);
  const table = decodeURIComponent(url.pathname.replace(/^\/rest\/v1\//, "").split("/")[0].split("?")[0]);
  if (!TABLES[table]) return json({ message: "table inconnue: " + table }, 404);
  const email = (context.data && context.data.email) || "";
  const method = request.method.toUpperCase();
  const wantRepr = (request.headers.get("Prefer") || "").includes("return=representation");

  // colonnes demandées (select)
  const selRaw = url.searchParams.get("select");
  let selectCols = "*";
  if (selRaw && selRaw !== "*") {
    const wanted = selRaw.split(",").map((s) => s.trim().split(":").pop());
    for (const c of wanted) if (!isCol(table, c)) return json({ message: "colonne inconnue: " + c }, 400);
    selectCols = wanted.join(",");
  }

  // filtres (tous les params sauf mots réservés)
  const RESERVED = new Set(["select", "order", "limit", "offset"]);
  const params = [];
  const where = [];
  for (const [k, v] of url.searchParams) {
    if (RESERVED.has(k)) continue;
    if (!isCol(table, k)) return json({ message: "filtre sur colonne inconnue: " + k }, 400);
    where.push(buildFilter(table, k, v, params));
  }
  // Scope private_to appliqué SAUF en accès machine full-access (MCP/Claude/Dan).
  if (table === "briefs" && !(context.data && context.data.fullAccess)) where.push(briefsScope(email, params));

  try {
    if (method === "GET") {
      let sql = `select ${selectCols} from ${table}`;
      if (where.length) sql += " where " + where.join(" and ");
      const ord = url.searchParams.get("order");
      if (ord) {
        const parts = ord.split(",").map((o) => {
          const [c, dir] = o.split(".");
          if (!isCol(table, c)) return null;
          return `${c} ${/desc/i.test(dir || "") ? "desc" : "asc"}`;
        }).filter(Boolean);
        if (parts.length) sql += " order by " + parts.join(",");
      }
      const lim = parseInt(url.searchParams.get("limit") || "", 10);
      if (Number.isFinite(lim)) sql += ` limit ${Math.min(Math.max(lim, 0), 10000)}`;
      const off = parseInt(url.searchParams.get("offset") || "", 10);
      if (Number.isFinite(off)) sql += ` offset ${Math.max(off, 0)}`;
      const { rows } = await pool.query(sql, params);
      return json(rows);
    }

    if (method === "POST") {
      let body = await request.json().catch(() => null);
      if (!body) return json({ message: "corps JSON attendu" }, 400);
      const list = Array.isArray(body) ? body : [body];
      if (!list.length) return json([]);
      const client = await pool.connect();
      try {
        await client.query("begin");
        const out = [];
        for (const rec of list) {
          const keys = Object.keys(rec).filter((k) => isCol(table, k) && k !== "id");
          const vals = keys.map((k) => paramForWrite(colType(table, k), rec[k]));
          const ph = keys.map((_, i) => "$" + (i + 1)).join(",");
          const ret = wantRepr ? " returning *" : "";
          const q = keys.length
            ? `insert into ${table} (${keys.join(",")}) values (${ph})${ret}`
            : `insert into ${table} default values${ret}`;
          const res = await client.query(q, vals);
          if (res.rows[0]) out.push(res.rows[0]);
          if (table === "briefs") {
            const row = res.rows[0] || rec;
            await emitEvent(client, { ndeg: row.ndeg, entree: row.entree, client: row.client, projet: row.projet, kind: "created", statut_new: row.statut, resp_new: row.responsable, summary: "Nouvelle entrée" });
          }
        }
        await client.query("commit");
        return json(wantRepr ? out : [], 201);
      } catch (e) { await client.query("rollback").catch(() => {}); throw e; }
      finally { client.release(); }
    }

    if (method === "PATCH" || method === "DELETE") {
      if (!where.length) return json({ message: "écriture sans filtre refusée" }, 400);
      const client = await pool.connect();
      try {
        await client.query("begin");
        // état avant (pour le journal) — limité aux briefs
        let before = [];
        if (table === "briefs") {
          const r = await client.query(`select * from ${table} where ${where.join(" and ")}`, params);
          before = r.rows;
        }
        let result;
        if (method === "DELETE") {
          result = await client.query(`delete from ${table} where ${where.join(" and ")}${wantRepr ? " returning *" : ""}`, params);
          if (table === "briefs") for (const b of before)
            await emitEvent(client, { ndeg: b.ndeg, client: b.client, projet: b.projet, kind: "deleted", statut_old: b.statut, resp_old: b.responsable, summary: "Supprimé" });
        } else {
          const body = await request.json().catch(() => ({}));
          const patch = body && typeof body === "object" ? body : {};
          const keys = Object.keys(patch).filter((k) => isCol(table, k) && k !== TABLES[table].pk);
          if (!keys.length) { await client.query("rollback"); return json({ message: "aucune colonne à modifier" }, 400); }
          // updated_at auto si la colonne existe
          if (isCol(table, "updated_at") && !keys.includes("updated_at")) { patch.updated_at = new Date().toISOString(); keys.push("updated_at"); }
          const setParams = params.slice(); // WHERE d'abord ($1..$W), puis les SET ($W+1..)
          const sets = keys.map((k) => { setParams.push(paramForWrite(colType(table, k), patch[k])); return `${k} = $${setParams.length}`; });
          result = await client.query(`update ${table} set ${sets.join(",")} where ${where.join(" and ")}${wantRepr ? " returning *" : ""}`, setParams);
          if (table === "briefs") for (const b of before) {
            const ch = kindFromChange(b, patch);
            if (ch) await emitEvent(client, { ndeg: b.ndeg, client: b.client, projet: b.projet, kind: ch.kind, statut_old: b.statut, statut_new: patch.statut ?? b.statut, resp_old: b.responsable, resp_new: patch.responsable ?? b.responsable, summary: ch.summary });
          }
        }
        await client.query("commit");
        return json(wantRepr ? (result.rows || []) : []);
      } catch (e) { await client.query("rollback").catch(() => {}); throw e; }
      finally { client.release(); }
    }

    return json({ message: "méthode non supportée" }, 405);
  } catch (e) {
    console.error("[pgrest]", method, table, e && e.message);
    return json({ message: "erreur SQL", detail: String((e && e.message) || e) }, 500);
  }
}
// ---- lecture directe (pour _feed.js côté serveur) --------------------------
export async function query(sql, params) {
  if (!pool) throw new Error("no db");
  return pool.query(sql, params);
}
